function com_tot=calculate_total_com(coms,m) % take CenterOfMasses and Masses

com_tot=(coms.com_RT*m.T+coms.com_RS*m.S+coms.com_RF*m.F+...
    coms.com_LT*m.T+coms.com_LS*m.S+coms.com_LF*m.F+...
    coms.com_TA*m.TA+coms.com_P*m.P)...
    /(2*m.T+2*m.S+2*m.F+m.TA+m.P)